### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by unknwon** [sirnewton01/godev#13]
Hey there,

This is a really awesome tool, especially it has intellisense. I also notice it supports remotes access, but I do quite understand how to use it, could you give more details?

BTW, it has `account` panel in the setting page, does that mean anything?

Cheers,
Joe.

**Comment by sirnewton01** [comment]
Hi,

The remote access is done using ssl/tls and a magic cookie (random number) to help prevent others from using your godev to gain access to your machine. There are a number of instructions in the README.md file under "Remote Access" to get you started. Many of the instructions are needed only for the first time you set it up.

Basically, you need to create an ssl/tls key using a special Go script that comes with your go installation. Then you need to secure the key so that nobody else on your system can copy it. Finally, you set environment variables to tell godev where the keys are so that it can use them to secure the connection.

When you launch godev in this mode it will provide you with a special URL that has the magic key in it. Keep this URL private so that you are the only one who can use your godev server.

I hope that this helps,
Chris

**Comment by unknwon** [comment]
Thanks! I'll try again.

How about the `account` one? Does that mean anything?

Cheers,
Joe.

**Comment by sirnewton01** [comment]
The account tab in the settings doesn't have any meaning at the moment. Godev is running in a single user mode while the web UI framework that it reuses can be used in hosted situations with multiple users.

Maybe some day I will investigate how to host a multi-user godev server.

**Comment by unknwon** [comment]
Probably can be used for log-in mode for remote access? So that one browser is good enough to code anywhere, anytime. 

For instance, it's quite useful when I'm not my computer but there are something I need to fix on the server; also for chromebook users who only have a browser, it's quite nice!

Cheers,
Joe.

**Comment by sirnewton01** [comment]
Godev should put a cookie in your browser with the magic key in it. So, once you connect to godev from your browser it will continue to work with the godev server until you restart the server, which will generate a new magic key.

Someone else recommended that I hook in google/twitter/fb authentication to godev so that you can sit down at any browser and authenticate using these credentials. I hope to look at this at some point.

**Comment by unknwon** [comment]
Yes right, 

> Someone else recommended that I hook in google/twitter/fb authentication to godev so that you can sit down at any browser and authenticate using these credentials. I hope to look at this at some point.

This will be really handy! Wait for that point. lol.

Thanks a lot!

Cheers,
Joe.
