### ISSUE TITLE
Mozilla Persona Authentication

### ISSUE THREAD

**Issue by unknwon** [sirnewton01/godev#19]
How to setup domain?

When I use GOHOST=XX godev force me to have certificate file and key file.

Did you miss anything in README to config this?

Thanks!

**Comment by unknwon** [comment]
Finally succeed with generated certificate file and key file. Probably doing this for HTTPS so I have to have those files and the Mozilla Persona Authentication just a kind of shortcut?

**Comment by sirnewton01** [comment]
It's good to hear that you got it set up. Yes, the persona authentication is useful in case you don't have the magic URL.

Is there anything that can be done better?

**Comment by unknwon** [comment]
Eh, I got another problem which is the Chrome OS seems like does not allow self-signed SSL anyway(at least I didn't find a way for hours). So could you give an option that like I completely understand the risk and I want to disable HTTPS and just HTTP. 

Thanks!

**Comment by sirnewton01** [comment]
That's too bad that Chrome OS won't allow you to click through for self-signed certificates like Chrome does.

I'm a little uncomfortable with allowing plain HTTP across a network even if you feel that you trust your network.

I will look into figuring out how to add self-signed certificates as trusted in Chrome/Chrome OS.

**Comment by unknwon** [comment]
Well, hope you can make it!

**Comment by unknwon** [comment]
I installed xcfe4 on Chomebook and Firefox, it's not easy to find a way to work through. I probably should use VIM on Chromebook...

**Comment by sirnewton01** [comment]
I'm hoping one of these might work:
http://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate

**Comment by sirnewton01** [comment]
I don't own a chromebook but I was able to make chrome trust my own server by making my own certificate authority and keys. I started by doing what is described in this guide:
http://www.g-loaded.eu/2005/11/10/be-your-own-ca/

Then I went into Chrome Settings -> Show Advanced Settings -> HTTP/SSL -> Authorities
I clicked the "Import..." button and imported the server-key-cert.pem file from the tutorial.

When I launched godev I set GOCERTFILE to "/etc/pki_jungle/myCA/certs/server.crt" and GOKEYFILE to "/etc/pki_jungle/myCA/private/server.key"

I can connect using chrome and it doesn't give me any kind of certificate error. I believe that you should be able to do the same with Chrome OS. Again, I don't have a Chrome OS machine around. I tried this with a Chrome OS virtualbox image but I think it is slightly broken.

Are you willing to try this out and see if it works for you on your chrome book? If it does can you let me know so that I can write a guide with this information?

Thanks,
Chris

**Comment by unknwon** [comment]
Thanks! Let me try it and I'll give back the result!

**Comment by sirnewton01** [comment]
Hi, I was wondering if you were able to get things working on your chromebook?
